name: manual trigger
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "Nagalakshmi"
jobs:
  manual:
    runs-on:  ubuntu-latest
    steps:
      - name: print name
        run: echo "hello ${{ github.event.inputs.name}}"
  